version: 2.1
jobs:
  check_whitespace:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: ./dev-scripts/check-trailing-whitespace
      - run:
          name: Check that all text files end in a trailing newline
          command: ./dev-scripts/check-trailing-newline
  check_bash:
    docker:
      - image: koalaman/shellcheck-alpine:v0.9.0
    steps:
      - run:
          name: Install dependencies
          command: apk add bash git openssh-client grep
      - checkout
      - run:
          name: Run static analysis on bash scripts
          command: ./dev-scripts/check-bash
  build_debian_package:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run:
          name: Enable multiarch builds with QEMU
          command: ./dev-scripts/enable-multiarch-docker
      - run:
          name: Build Debian package
          command: ./dev-scripts/build-debian-pkg "linux/arm/v7,linux/amd64"
      - run:
          name: Print Debian package contents
          command: |
            set -x
            while read -r file; do
              echo "${file}"
              dpkg --contents "${file}"
            done < <(find . -name '*.deb')
      - persist_to_workspace:
          root: build
          paths:
            - ./*/*.deb
      - store_artifacts:
          path: build
workflows:
  test:
    jobs:
      - check_whitespace
      - check_bash
      - build_debian_package
