#!/bin/bash

# Build uStreamer Debian package.

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

PKG_VERSION="$(date '+%Y%m%d%H%M%S')"
readonly PKG_VERSION

# Use plain Docker build progress output when we're running in CI.
DOCKER_PROGRESS='auto'
if [[ -n "${CI:-}" ]]; then
  DOCKER_PROGRESS='plain'
fi
readonly DOCKER_PROGRESS

DOCKER_BUILDKIT=1 docker build \
  --file Dockerfile \
  --build-arg PKG_VERSION="${PKG_VERSION}" \
  --target=artifact \
  --progress="${DOCKER_PROGRESS}" \
  --output "type=local,dest=$(pwd)/build/" \
  .
