#!/bin/bash

# Build uStreamer Debian package.
#
# Usage:
#   build-debian-pkg
#

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

readonly BUILD_TARGETS='linux/arm64'

PKG_BUILD_NUMBER="$(date '+%Y%m%d%H%M%S')"
readonly PKG_BUILD_NUMBER

# Use plain Docker build progress output when we're running in CI.
DOCKER_PROGRESS='auto'
if [[ -n "${CI:-}" ]]; then
  DOCKER_PROGRESS='plain'
fi
readonly DOCKER_PROGRESS

DOCKER_BUILDKIT=1 docker buildx build \
  --file Dockerfile \
  --platform "${BUILD_TARGETS}" \
  --build-arg PKG_BUILD_NUMBER="${PKG_BUILD_NUMBER}" \
  --target=artifact \
  --progress="${DOCKER_PROGRESS}" \
  --output "type=local,dest=$(pwd)/build/" \
  .
